### PR TITLE
Ensure Non-Met start codons map to Met on translation

### LINKED ISSUE #305: Translate should have a setting to set first codon to M
testTranslation, _ := codon.Translate(gfpDnaSequence, codon.GetCodonTable(11))

This fails in the case of  `gfpDnaSequence := "TTGGCT...TAA"`, which is perfectly valid for a start codon.

### PR DESCRIPTION
**Pull request by carreter**
Also makes Translate() return an error if an invalid start codon is received

Fixes #305.

### CODE REVIEW

File: synthesis/codon/codon_test.go [hunk 1]
```diff
@@ -21,6 +21,26 @@ func TestTranslation(t *testing.T) {
...
+}
+
+func TestTranslationErrorsOnIncorrectStartCodon(t *testing.T) {
+	badSequence := "GGG"
+
+	if _, gotErr := Translate(badSequence, GetCodonTable(11)); gotErr == nil {
+		t.Errorf("Translation should return an error if given an incorrect start codon")
+	}
+}
+
```
Comment (Koeng101) [inline synthesis/codon/codon_test.go:43]: Great tests!

**Review by Koeng101 — APPROVED** [review]
This looks great to me, and is exactly the kind of checks we needed. Thanks!
